# Cointegration Tests

In [1]:
import warnings
import pandas as pd
import numpy as np
import yfinance as yf
import statsmodels.api as sm
warnings.filterwarnings("ignore")

In [2]:
import jtest as jt
import Traditional_Partner_Selection as tps
import Cointegration_coeeficient_tests as cct

In [3]:
ticker_list = ["AAL", "AAP", "AAPL", "GLD", "GOOG", "TSLA", "GDX", "GOOGL"]

In [4]:
data = np.log(yf.download(ticker_list, period="10y", interval="1d")["Adj Close"])
data

[*********************100%***********************]  8 of 8 completed


AAL       AAP      AAPL       GDX       GLD      GOOG  \
Date                                                                     
2013-04-01  2.754647  4.340114  2.582491  3.535976  5.041294  2.993477   
2013-04-02  2.697242  4.346047  2.584541  3.493150  5.026705  3.008160   
2013-04-03  2.683810  4.337439  2.589646  3.446656  5.015490  2.999711   
2013-04-04  2.694060  4.338412  2.579713  3.474584  5.012567  2.985809   
2013-04-05  2.695971  4.323088  2.569089  3.470031  5.029195  2.970576   
...              ...       ...       ...       ...       ...       ...   
2023-03-22  2.626117  4.732683  5.061519  3.419692  5.211888  4.646504   
2023-03-23  2.612273  4.710791  5.068464  3.443938  5.224348  4.665889   
2023-03-24  2.618855  4.707998  5.076735  3.451574  5.213032  4.664005   
2023-03-27  2.634762  4.742669  5.064366  3.450622  5.203732  4.635311   
2023-03-28  2.637628  4.751346  5.060377  3.475377  5.211888  4.618679   

               GOOGL      TSLA  
Date                            
2013-04-01  2.998219  1.074547  
2013-04-02  3.012901  1.083837  
2013-04-03  3.004453  1.007958  
2013-04-04  2.990551  1.029858  
2013-04-05  2.975318  1.014506  
...              ...       ...  
2023-03-22  4.638315  5.253058  
2023-03-23  4.659658  5.258641  
2023-03-24  4.658142  5.249180  
2023-03-27  4.629472  5.256505  
2023-03-28  4.615417  5.242752  

[2517 rows x 8 columns]

In [5]:
returns_data = data.diff().dropna()
returns_data

AAL       AAP      AAPL       GDX       GLD      GOOG  \
Date                                                                     
2013-04-02 -0.057405  0.005933  0.002050 -0.042826 -0.014588  0.014682   
2013-04-03 -0.013432 -0.008609  0.005106 -0.046493 -0.011215 -0.008448   
2013-04-04  0.010250  0.000974 -0.009934  0.027927 -0.002923 -0.013902   
2013-04-05  0.001910 -0.015324 -0.010624 -0.004553  0.016629 -0.015234   
2013-04-08  0.007605 -0.003961  0.007087 -0.011763 -0.004263 -0.010527   
...              ...       ...       ...       ...       ...       ...   
2023-03-22 -0.039026 -0.053057 -0.009145  0.018495  0.016877 -0.015424   
2023-03-23 -0.013844 -0.021893  0.006945  0.024246  0.012460  0.019385   
2023-03-24  0.006581 -0.002793  0.008271  0.007636 -0.011316 -0.001884   
2023-03-27  0.015908  0.034671 -0.012369 -0.000951 -0.009300 -0.028694   
2023-03-28  0.002865  0.008678 -0.003988  0.024755  0.008156 -0.016633   

               GOOGL      TSLA  
Date                            
2013-04-02  0.014682  0.009290  
2013-04-03 -0.008448 -0.075879  
2013-04-04 -0.013902  0.021900  
2013-04-05 -0.015234 -0.015352  
2013-04-08 -0.010527  0.011058  
...              ...       ...  
2023-03-22 -0.014883 -0.033085  
2023-03-23  0.021344  0.005582  
2023-03-24 -0.001516 -0.009461  
2023-03-27 -0.028670  0.007326  
2023-03-28 -0.014055 -0.013753  

[2516 rows x 8 columns]

### Ranking Quadruples based on Spearman and Kendall Correlation

In [6]:
tps.spearman_rank_correlation(returns_data, n=2)

Spearman Rank Sum
GOOG with ('AAL', 'AAPL', 'GOOGL', 'TSLA')           2.250494
GOOGL with ('AAL', 'AAPL', 'GOOG', 'TSLA')           2.246310

In [7]:
tps.kendall_rank_correlation(returns_data, n=2)

Kendall Rank Sum
GOOG with ('AAL', 'AAPL', 'GOOGL', 'TSLA')          1.817211
GOOGL with ('AAL', 'AAPL', 'GOOG', 'TSLA')          1.813690

### Engle Granger Causality Test

#### Using OLS

In [8]:
cct.ols_regress_coeff(data[["AAPL", "GOOG"]])

{0.11743714702832997: {'AAPL Weight': -1.5529671083147845, 'GOOG Weight': 1}}

#### Using VAR

In [9]:
cct.granger_causation_matrix(data[["AAPL", "GOOG"]])

'Insignificant Causation'

### Johanssen Test

#### Using Built In Function

In [10]:
cct.johansen_test(data[["AAPL", "GOOG","TSLA"]], alpha=0.01)

'Insignificant: Cannot Reject null hypothesis'

#### Written Function

In [11]:
jt.coint_johansen(data[["AAPL", "GOOG","TSLA"]], 0, 1)

--------------------------------------------------
--> Trace Statistics
variable statistic Crit-90% Crit-95%  Crit-99%
r = 0 	 15.8839 27.0669 29.7961 35.4628
r = 1 	 5.2165 13.4294 15.4943 19.9349
r = 2 	 0.4927 2.7055 3.8415 6.6349
--------------------------------------------------
--> Eigen Statistics
variable statistic Crit-90% Crit-95%  Crit-99%
r = 0 	 10.6674 18.8928 21.1314 25.865
r = 1 	 4.7238 12.2971 14.2639 18.52
r = 2 	 0.4927 2.7055 3.8415 6.6349
--------------------------------------------------
eigenvectors:
 [[ 5.94362255  1.00484655 -2.42884675]
 [-4.99652943 -5.21806426  1.26658095]
 [-1.84001368  1.68113165  0.19796783]]
--------------------------------------------------
eigenvalues:
 [0.00423255 0.0018765  0.00019587]
--------------------------------------------------
